RANGER-1982i:Error Improvement for Analytics Metric of Ranger Admin and Ranger Kms
Signed-off-by: Mehul Parikh <mehul@apache.org>

diff --git a/kms/scripts/ranger-kms b/kms/scripts/ranger-kms
--- a/kms/scripts/ranger-kms
+++ b/kms/scripts/ranger-kms
@@ -157,6 +157,10 @@ killRangerKMSPid () {
 	fi
 }
 metric(){
+  if [ "$JAVA_HOME" == "" ]; then
+    echo "[E] JAVA_HOME environment variable not defined, aborting Apache Ranger KMS metric collection"
+    exit 1;
+  fi
 	java  ${JAVA_OPTS} org.apache.hadoop.crypto.key.kms.server.KMSMetricUtil ${arg2} ${arg3} 2>/dev/null
 }
 if [ "${action}" == "START" ]; then
