RANGER-1982 : Error Improvement for Analytics Metric of Ranger Admin and Ranger Kms
Signed-off-by: Mehul Parikh <mehul@apache.org>

diff --git a/kms/scripts/ranger-kms b/kms/scripts/ranger-kms
--- a/kms/scripts/ranger-kms
+++ b/kms/scripts/ranger-kms
@@ -143,7 +143,7 @@ killRangerKMSPid () {
 }
 metric(){
   if [ "$JAVA_HOME" == "" ]; then
-    echo "[E] JAVA_HOME environment variable not defined, aborting Apache Ranger KMS metric collection"
+    echo "[E] JAVA_HOME environment variable not defined, aborting Apache Ranger KMS metric collection" 1>&2;
     exit 1;
   fi
 	java  ${JAVA_OPTS} org.apache.hadoop.crypto.key.kms.server.KMSMetricUtil ${arg2} ${arg3} 2>/dev/null
