RANGER-1026 : Ranger service to generate PID
Signed-off-by: Velmurugan Periasamy <vel@apache.org>

diff --git a/kms/scripts/ranger-kms b/kms/scripts/ranger-kms
--- a/kms/scripts/ranger-kms
+++ b/kms/scripts/ranger-kms
@@ -75,30 +75,74 @@ then
 fi
 
 KMS_CONF_DIR=${RANGER_KMS_EWS_DIR}/webapp/WEB-INF/classes/conf
-
+pidf="/var/run/ranger/rangerkms.pid"
 JAVA_OPTS="${JAVA_OPTS} -Dcatalina.base=${RANGER_KMS_EWS_DIR} -Dkms.config.dir=${KMS_CONF_DIR} -Dkms.log.dir=${TOMCAT_LOG_DIR} -cp ${RANGER_KMS_EWS_CONF_DIR}:${RANGER_KMS_EWS_LIB_DIR}/*:${RANGER_KMS_EWS_DIR}/webapp/lib/*:${JAVA_HOME}/lib/*:${RANGER_HADOOP_CONF_DIR}/*:$CLASSPATH "
-
+createRangerKMSPid () {
+	SLEEP_TIME_AFTER_START=5
+	nohup java -D${PROC_NAME} ${JAVA_OPTS} ${START_CLASS_NAME} ${KMS_CONFIG_FILENAME} > ${TOMCAT_LOG_FILE} 2>&1 &
+	VALUE_OF_PID=$!
+	echo "Starting Apache Ranger KMS Service"
+	sleep $SLEEP_TIME_AFTER_START
+	if ps -p $VALUE_OF_PID > /dev/null
+	then
+		echo $VALUE_OF_PID > ${pidf}
+		chown ranger ${pidf}
+		chmod 660 ${pidf}
+		pid=`cat $pidf`
+		echo "Apache Ranger KMS Service with pid ${pid} has started."
+	else
+		echo "Apache Ranger KMS Service failed to start"
+		exit 1
+	fi
+}
+killRangerKMSPid () {
+	SLEEP_TIME_AFTER_KILL=5
+	if [ -f "$pidf" ] ; then
+		nohup java ${JAVA_OPTS} ${STOP_CLASS_NAME} ${KMS_CONFIG_FILENAME} > ${TOMCAT_STOP_LOG_FILE} 2>&1
+		pid=`cat $pidf` > /dev/null 2>&1
+		echo "Found Apache Ranger KMS Service with pid $pid, killing..."
+		kill $pid
+		sleep $SLEEP_TIME_AFTER_KILL
+		# if process is still around, use kill -9
+		if ps -p $pid > /dev/null ; then
+			echo "Initial kill failed, getting serious now..."
+			kill -9 $pid
+		fi
+		if ps -p $pid > /dev/null ; then
+			echo "Wow, even kill -9 failed, giving up! Sorry.."
+			exit 1
+		else
+			rm -rf $pidf
+			echo "Apache Ranger KMS Service with pid ${pid} has been stopped."
+		fi
+	else
+		echo "Apache Ranger KMS Service is not running"
+	fi
+}
 if [ "${action}" == "START" ]; then
-	echo "+ java -D${PROC_NAME} ${JAVA_OPTS} ${START_CLASS_NAME} ${KMS_CONFIG_FILENAME} "
-	java -D${PROC_NAME} ${JAVA_OPTS} ${START_CLASS_NAME} ${KMS_CONFIG_FILENAME} > ${TOMCAT_LOG_FILE} 2>&1 &
-	echo "Apache Ranger KMS has started."
-	exit
+	if [ -f "$pidf" ] ; then
+		pid=`cat $pidf`
+		if [ "${pid}" != "" ]
+		then
+			echo "Apache Ranger KMS Service is already running [pid={$pid}]"
+			exit 1
+		fi
+	else
+		createRangerKMSPid
+		exit
+	fi
 elif [ "${action}" == "STOP" ]; then
-	java ${JAVA_OPTS} ${STOP_CLASS_NAME} ${KMS_CONFIG_FILENAME} > ${TOMCAT_STOP_LOG_FILE} 2>&1
-	echo "Apache Ranger KMS has been stopped."
+	killRangerKMSPid
 	exit
 elif [ "${action}" == "RESTART" ]; then
-	echo "Restarting Apache Ranger KMS"
-	java ${JAVA_OPTS} ${STOP_CLASS_NAME} ${KMS_CONFIG_FILENAME} > ${TOMCAT_STOP_LOG_FILE} 2>&1
-	echo "Apache Ranger KMS has been stopped."
-	echo "Starting Apache Ranger KMS."
-	java -D${PROC_NAME} ${JAVA_OPTS} ${START_CLASS_NAME} ${KMS_CONFIG_FILENAME} > ${TOMCAT_LOG_FILE} 2>&1 &
-	echo "Apache Ranger KMS has started successfully."
+	echo "Restarting Apache Ranger KMS Service"
+	killRangerKMSPid
+	createRangerKMSPid
 	exit
 elif [ "${action}" == "VERSION" ]; then
 	( cd ${RANGER_KMS_LIB_DIR} ; java -cp ranger-util-*.jar org.apache.ranger.common.RangerVersionInfo )
 	exit
-else 
+else
         echo "Invalid argument [$1];"
         echo "Usage: Only start | stop | restart | version, are supported."
         exit;
