RANGER-177 : Run Ranger usersync as non-root user
Signed-off-by: Velmurugan Periasamy <vel@apache.org>

diff --git a/unixauthservice/scripts/initd b/unixauthservice/scripts/initd
--- a/unixauthservice/scripts/initd
+++ b/unixauthservice/scripts/initd
@@ -23,23 +23,56 @@
 # Short-Description: Start/Stop Ranger Usersync
 ### END INIT INFO
 
+LINUX_USER=ranger
 BIN_PATH=/usr/bin
 MOD_NAME=ranger-usersync
+pidf=/var/run/ranger/usersync.pid
+pid=""
+if [ -f ${pidf} ]
+then
+    pid=`cat $pidf`
+fi
 
 case $1 in
 	start)
-		${BIN_PATH}/${MOD_NAME} start
+	    if [ "${pid}" != "" ]
+	    then
+	        echo "Ranger Usersync Service is already running"
+		    exit 1
+		 else
+		 	echo "Starting Ranger Usersync."
+		    /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
+	    fi
 		;;
 	stop)
-		${BIN_PATH}/${MOD_NAME} stop
+	    if [ "${pid}" != "" ]
+        then
+            echo "Stopping Ranger Usersync."
+            /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
+        else
+            echo "Ranger Usersync Service is NOT running"
+            exit 1
+        fi
 		;;
 	restart)
-		echo "Stopping Apache Ranger Usersync."
-		${BIN_PATH}/${MOD_NAME} stop
-		echo "Starting Apache Ranger Usersync."
-		${BIN_PATH}/${MOD_NAME} start
+        if [ "${pid}" != "" ]
+        then
+            echo "Stopping Ranger Usersync."
+            /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
+            sleep 10
+        fi
+        echo "Starting Ranger Usersync."
+        /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
 		;;
+	status)
+        if [ "${pid}" != "" ]
+        then
+            echo "Ranger Usersync Service is running [pid={$pid}]"
+        else
+            echo "Ranger Usersync Service is NOT running."
+        fi
+	 ;;
 	*)
-		echo "Invalid argument [$1]; Only start | stop | restart, are supported."
+		echo "Invalid argument [$1]; Only start | stop | restart | status, are supported."
 		exit 1
 	esac
