ARGUS-137 Rename Apache Argus to Apache Ranger on the codebase/config
Signed-off-by: sneethiraj <sneethir@apache.org>

diff --git a/embededwebserver/scripts/ranger-admin b/embededwebserver/scripts/ranger-admin
--- a/embededwebserver/scripts/ranger-admin
+++ b/embededwebserver/scripts/ranger-admin
@@ -16,15 +16,22 @@
 # limitations under the License.
 
 
-export JAVA_HOME=
-export PATH=$JAVA_HOME/bin:$PATH
+LINUX_USER=ranger
+BIN_PATH=/usr/bin
 
-XAPOLICYMGR_DIR=/usr/lib/xapolicymgr
-XAPOLICYMGR_EWS_DIR=${XAPOLICYMGR_DIR}/ews
-cd ${XAPOLICYMGR_EWS_DIR}
-if [ ! -d logs ]
-then
-	mkdir logs
-fi
-java -Xmx1024m -Xms1024m -Dcatalina.base=${XAPOLICYMGR_EWS_DIR} -cp "${XAPOLICYMGR_EWS_DIR}/lib/*:${XAPOLICYMGR_DIR}/xasecure_jaas/*:${XAPOLICYMGR_DIR}/xasecure_jaas:${JAVA_HOME}/lib/*" com.xasecure.server.tomcat.EmbededServer > logs/catalina.out 2>&1 &
-echo "XAPolicyManager has started successfully."
+case $1 in
+start)
+	/bin/su --login  $LINUX_USER "${BIN_PATH}/start-ranger-admin"
+	;;
+stop)
+	/bin/su --login  $LINUX_USER "${BIN_PATH}/stop-ranger-admin"
+    ;;
+restart)
+	/bin/su --login  $LINUX_USER "${BIN_PATH}/stop-ranger-admin.sh"  && sleep 30
+	/bin/su --login  $LINUX_USER "${BIN_PATH}/start-ranger-admin.sh"
+
+	;;
+*)
+	echo "Invalid argument [$1]; Only start|stop|restart are supported."
+    exit 1
+esac
